name: Azure container app CI/CD

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    paths:
      - '!materials/**'
      - '!README.md'
      - 'app/**'
      - 'Dockerfile'
    branches: 
      - main

  # Allow manually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.date.outputs.date}}
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: main

      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}} 

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d').$BUILD_NUMBER"

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{version}"
          replace: ${{ steps.date.outputs.date }}
          include: "app/*.html"
          regex: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PWD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrfyi.azurecr.io/nodeapp:${{ steps.date.outputs.date }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az extension add -n containerapp --yes
            echo "Starting Deploying"
            az containerapp update -n ${{ secrets.ACA_NAME }} -g ${{ secrets.AZURE_RG }} -i ${{ secrets.ACR_URL }}/nodeapp:${{ needs.build.outputs.tag }} --debug
